# dimensions and sizes
geom_dim: 6
cats_dim: 8
hid_dim: 64
num_layers: 5
# network settings
conv: gcn  # type of graph convolution ("custom" = GCN, "gat" = GATv2, "gin" = GIN)
heads: 4  # in the case of GAT(v2)
matching: false
message_gain: 0.1
graph_reg: true
graph_vec_weight: 5e-4
aggr: add
drop: 0
# optimization
cuda: true
distance: margin
margin: 0.1
kernel_loss: False
n_epochs: 100
lr: 1e-4
bs: 64
step: 10
# data and paths
hard: true  # if hard negatives
data: rplan
weak_label: sged
path_checkpoint: /home/casper/PycharmProjects/LayoutGKN/models
path_data: /home/casper/PycharmProjects/LayoutGKN/data
path_rplan: /home/casper/Documents/Data/rplan/dataset/floorplan_dataset   # RPLAN images (raw dataset)
path_msd: /home/casper/Documents/Data/msd
# remaining
print_freq: 0.1
# run
sweep: false
cross_val: false