# TODO: make hierarchical (eg, model.dim_geom)
# dimensions and sizes
geom_dim: 6
cats_dim: 8
hid_dim: 64
num_layers: 5
# network settings
matching: false
message_gain: 0.1
graph_reg: true
graph_vec_weight: 5e-4
aggr: add
drop: 0
# optimization
cuda: true
distance: margin
margin: 0.1
kernel_loss: False
n_epochs: 100
lr: 1e-4
bs: 64
step: 10
print_freq: 0.1
# data and paths
hard: true  # hard negatives?
data: rplan
weak_label: sged
path_checkpoint: /home/casper/PycharmProjects/LayoutGKN/models
path_data: /home/casper/PycharmProjects/LayoutGKN/data
path_rplan: /home/casper/Documents/Data/rplan/dataset/floorplan_dataset
path_msd: /home/casper/Documents/Data/msd
# run
sweep: false
cross_val: false
# w&b
wandb:
  api_key: c52c284e0d6ab885356b0f83dd3725d320154b96
  entity: casper-van-engelenburg
  project: LayoutGKN
